### ISSUE TITLE
:memo: Compléter le "About" :speaking_head: 

### ISSUE THREAD

**Issue by adriens** [denispeyrusaubes/certificate-management-demo#1]
![image](https://user-images.githubusercontent.com/5235127/195708194-388d9ca5-d46a-4213-bb44-e73431a324c8.png)

**Comment by denispeyrusaubes** [comment]
Done
https://github.com/denispeyrusaubes/certificate-management-demo

**Comment by adriens** [comment]
👍 
![image](https://user-images.githubusercontent.com/5235127/197923903-bd57428d-2359-47b5-a63a-3815306e48fa.png)
